name: Build Vite Application and Docker Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./vote-ui

      - name: Build application
        run: npm run build
        working-directory: ./vote-ui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t vote-ui:latest .
        working-directory: ./vote-ui

      - name: Tag Docker image with version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "tag version: $TAG_VERSION"
          repo=${{ github.repository }}
          lower_repo=$(echo "$repo" | tr '[:upper:]' '[:lower:]')
          docker tag vote-ui:latest ghcr.io/${lower_repo}:${TAG_VERSION}
          docker tag vote-ui:latest ghcr.io/${lower_repo}:latest

        working-directory: ./vote-ui

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        working-directory: ./vote-ui

      - name: Push Docker image with version tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          repo=${{ github.repository }}
          lower_repo=$(echo "$repo" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${lower_repo}:${TAG_VERSION}
          docker push ghcr.io/${lower_repo}:latest
        working-directory: ./vote-ui
